### ISSUE TITLE
Hey, what's `light` in the i3wm dotfile (in the screen brightness controls)

### ISSUE THREAD

**Issue by trn1ty** [patrickbolle/dotfiles#1]
Trying to get the media keys working for the backlight on my T420 and I found your dotfiles. I saw you have 
```bindsym XF86MonBrightnessUp exec light -A 5 && notify-send --expire-time=20 "LCD Backlight $(printf %.0f%% $(light -G))"```
```bindsym XF86MonBrightnessDown exec light -U 5 && notify-send --expire-time=20 "LCD Backlight $(printf %.0f%% $(light -G))"```
set up for the brightness keys but an `apt install` didn't pull anything up for `light`. Is this a custom bash script or some buildable program somewhere?

Thanks for any help.

**Comment by patrickbolle** [comment]
Hi! 

Light is referencing this package: https://github.com/haikarainen/light

Should be able to download the dev here - https://github.com/haikarainen/light/releases/

Hope that helps!

**Comment by trn1ty** [comment]
Thank you so much!

You've earned this Github star; I've been trying to figure out how to adjust the backlight in i3wm for a long time and after adding a bit of code from your dotfile and installing light it just suddenly worked.
